# Generated by Django 2.2.7 on 2019-11-27 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lp7', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboutHeading', models.TextField(help_text='Please enter your heading here.', max_length=50, verbose_name='Heading Text')),
                ('aboutParagraph1', models.TextField(help_text='Please enter your paragraph.', max_length=2000, verbose_name='Paragraph 1')),
                ('aboutParagraph2', models.TextField(help_text='Please enter your paragraph.', max_length=2000, verbose_name='Paragraph 2')),
                ('aboutImage', models.ImageField(default='About Image', help_text='Please upload the image for About section', upload_to='../media/images/about')),
            ],
            options={
                'verbose_name_plural': 'About Section',
            },
        ),
        migrations.CreateModel(
            name='BGimages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfectBG', models.ImageField(help_text='Please upload the background image for Perfect Match Section', upload_to='../media/images/backgrounds', verbose_name='Perfect Match Background')),
                ('memberBG', models.ImageField(help_text='Please upload the background image for Members Logo Section', upload_to='../media/images/backgrounds', verbose_name='Member Logos Background')),
                ('locationPageBG', models.ImageField(default='Locations Page BG', help_text='Please upload the background image for Locations page', upload_to='../media/images/backgrounds', verbose_name='Locations Page Background')),
                ('locationDetailBG', models.ImageField(default='Location Detail Page BG', help_text='Please upload the background image for Location Detail page', upload_to='../media/images/backgrounds', verbose_name='Location Detail Page Background')),
                ('contactPageBG', models.ImageField(default='Contact Page BG', help_text='Please upload the background image for Contact page', upload_to='../media/images/backgrounds', verbose_name='Contact Page Background')),
                ('eventPageListBG', models.ImageField(default='Event List Page BG', help_text='Please upload the background image for Event List page', upload_to='../media/images/backgrounds', verbose_name='Event List Page Background')),
                ('eventDetailPageBG', models.ImageField(default='Event Detail Page BG', help_text='Please upload the background image for Event Detail page', upload_to='../media/images/backgrounds', verbose_name='Event Detail Page Background')),
                ('promotionListPageBG', models.ImageField(default='Promotion List Page BG', help_text='Please upload the background image for Promotion List page', upload_to='../media/images/backgrounds', verbose_name='Promotion List Page Background')),
                ('promotionDetailPageBG', models.ImageField(default='Promotion Detail Page BG', help_text='Please upload the background image for Promotion Detail page', upload_to='../media/images/backgrounds', verbose_name='Promotion Detail Page Background')),
                ('packageDetailPageBG', models.ImageField(default='Package Detail Page BG', help_text='Please upload the background image for Package Detail page', upload_to='../media/images/backgrounds', verbose_name='Package Detail Page Background')),
                ('homeHeadPageBG', models.ImageField(default='Home Head Section BG', help_text='Please upload the background image for Home Head Section page', upload_to='../media/images/backgrounds', verbose_name='Home Head Section Background')),
                ('aboutPageBG', models.ImageField(default='About Page BG', help_text='Please upload the background image for Home About page', upload_to='../media/images/backgrounds', verbose_name='About Page Background')),
                ('galleryPageBG', models.ImageField(default='gallery Page BG', help_text='Please upload the background image for gallery page', upload_to='../media/images/backgrounds', verbose_name='Gallery Page Background')),
                ('eventFormBG', models.ImageField(default='event form', help_text='Please upload the background image for event Form', upload_to='../media/images/backgrounds', verbose_name='Event Form Background')),
                ('packageFormBG', models.ImageField(default='Package form', help_text='Please upload the background image for package Form', upload_to='../media/images/backgrounds', verbose_name='package Form Background')),
            ],
            options={
                'verbose_name_plural': 'Background Images Section',
            },
        ),
        migrations.CreateModel(
            name='ContactedUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Sender's Name.", max_length=50, verbose_name='Name')),
                ('email', models.EmailField(help_text="Sender's Email", max_length=254, verbose_name='Email')),
                ('phone', models.CharField(default='', help_text="Sender's Phone Number", max_length=15, verbose_name='Phone Number')),
                ('message', models.TextField(help_text="Sender's Message", verbose_name='Message')),
            ],
            options={
                'verbose_name_plural': 'Contact Us Form',
            },
        ),
        migrations.CreateModel(
            name='eventBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Sender's Name.", max_length=50, verbose_name='Name')),
                ('email', models.EmailField(help_text="Sender's Email", max_length=254, verbose_name='Email')),
                ('phone', models.CharField(default='', help_text="Sender's Phone Number", max_length=15, verbose_name='Phone Number')),
                ('organization', models.CharField(help_text="Sender's Organization Name.", max_length=50, verbose_name='Organization')),
                ('eventName', models.CharField(help_text='Name of event.', max_length=150, verbose_name='Event Name')),
                ('eventDate', models.DateField(blank=True, help_text='Event Date.', null=True, verbose_name='Event Date')),
                ('eventTime', models.TimeField(default=datetime.time(0, 0), help_text='Event Time.', verbose_name='Event Time')),
                ('eventDetail', models.TextField(help_text='Event Detail.', verbose_name='Event Detail')),
                ('eventGuest', models.IntegerField(verbose_name='Expected No. of guest in event')),
                ('eventLocation', models.CharField(default='Location', max_length=50, verbose_name='Event Location')),
            ],
            options={
                'verbose_name_plural': 'Event Booking Form',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventTitle', models.CharField(blank=True, help_text='Please enter your event title here.', max_length=500, verbose_name='Event Title')),
                ('eventImage', models.ImageField(help_text='Please upload the event image', upload_to='../media/images/events/', verbose_name='Event Image')),
                ('eventText', models.TextField(blank=True, help_text='Please enter the detail of event.', max_length=2000, verbose_name='Event Detail')),
                ('eventLocation', models.CharField(blank=True, help_text='Please enter the location of event.', max_length=100, verbose_name='Event Location')),
                ('eventDate', models.DateField(blank=True, help_text='Please select the date of your event.', null=True, verbose_name='Event Date')),
                ('eventTime', models.TimeField(blank=True, help_text='Please select the starting time of your event.', null=True, verbose_name='Event Time')),
                ('slug', models.SlugField(default='', unique=True)),
                ('status', models.CharField(choices=[('', ''), ('Active', 'Active'), ('Expire', 'Expire')], default='', help_text='Select the status of event.', max_length=10, verbose_name='Event Status')),
            ],
            options={
                'verbose_name_plural': 'Events Section',
            },
        ),
        migrations.CreateModel(
            name='EventsHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventDetailText', models.TextField(blank=True, help_text='Please enter some paragraph for event detail page.', verbose_name='Event Detail Page Text')),
                ('eventDetailImage', models.ImageField(blank=True, default='Event detail image', help_text='Please upload the image file for event detail page.', upload_to='../media/images/events')),
            ],
            options={
                'verbose_name_plural': 'Events Page Heading',
            },
        ),
        migrations.CreateModel(
            name='galleryISD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galleryISDimage', models.ImageField(help_text='Please upload the image for Gallery Islamabad.', upload_to='../media/images/gallery/ISD/', verbose_name='Gallery Image')),
                ('galleryISDimageName', models.CharField(help_text='please enter the name of image.', max_length=30, verbose_name='Image Name')),
                ('galleryISDevent', models.CharField(help_text='Please enter the name of event where the image captured.', max_length=80, verbose_name='Image Event')),
            ],
            options={
                'verbose_name_plural': 'Gallery Islamabad',
            },
        ),
        migrations.CreateModel(
            name='galleryRWP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galleryRWPimage', models.ImageField(help_text='Please upload the image for Gallery Rawalpindi.', upload_to='../media/images/gallery/RWP/', verbose_name='Gallery Image')),
                ('galleryRWPimageName', models.CharField(help_text='please enter the name of image.', max_length=30, verbose_name='Image Name')),
                ('galleryRWPevent', models.CharField(help_text='Please enter the name of event where the image captured.', max_length=80, verbose_name='Image Event')),
            ],
            options={
                'verbose_name_plural': 'Gallery Rawalpindi',
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LocationImage', models.ImageField(help_text='Please upload location image.', upload_to='../media/images/locations', verbose_name='Location Image')),
                ('LocationName', models.CharField(default='', help_text='Please enter the location name.', max_length=50, verbose_name='Location Name')),
                ('LocationAddress', models.TextField(blank=True, help_text='Enter the detailed address.', max_length=500, verbose_name='Location Address')),
                ('LocationPhone', models.CharField(blank=True, help_text='Enter the PTCL number for location.', max_length=30, verbose_name='PTCL Number')),
                ('LocationMobile', models.CharField(blank=True, help_text='Enter Mobile/Whatsapp number for location.', max_length=30, verbose_name='Mobile Number')),
                ('LocationEmailID', models.CharField(blank=True, help_text='Enter the Email address for location.', max_length=50, verbose_name='Email Address')),
                ('LocationWeb', models.CharField(blank=True, help_text='Enter the web address for location.', max_length=50, verbose_name='Web Address ')),
                ('slug', models.SlugField(default='', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Locations Section',
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logoImage', models.ImageField(help_text='Please upload the website logo here.', upload_to='../media/images/')),
                ('altTitle', models.CharField(default='Alt text', help_text='Enter Alt text for image.', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Logo Section',
            },
        ),
        migrations.CreateModel(
            name='LP7features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featureText', models.TextField(help_text='Please enter your featured text.', max_length=200, verbose_name='Featured Text')),
            ],
            options={
                'verbose_name_plural': 'Features Section',
            },
        ),
        migrations.CreateModel(
            name='LP7MembersLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logoImage', models.ImageField(help_text='Please upload the new member logo.', upload_to='../media/images/members/', verbose_name='Member Logo')),
            ],
            options={
                'verbose_name_plural': 'Members Section',
            },
        ),
        migrations.CreateModel(
            name='LP7Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testiImage', models.ImageField(help_text='Please upload the image of testimonial.', upload_to='../media/images/testimonials', verbose_name='Testimonial Image')),
                ('testiText', models.TextField(help_text='Please enter the text of text of review.', max_length=1500, verbose_name='Testimonial Review')),
                ('testiName', models.CharField(help_text='Please enter the name of testimonial.', max_length=100, verbose_name='Testimonial Name')),
                ('testiTitle', models.CharField(help_text='Please enter the title of testimonial.', max_length=50, verbose_name='Testimonial Title')),
                ('testiCompany', models.CharField(blank=True, help_text='Please enter the name of testimonial company.', max_length=50, verbose_name='Testimonial Company')),
            ],
            options={
                'verbose_name_plural': 'Testimonial Section',
            },
        ),
        migrations.CreateModel(
            name='PackagePriceFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featureName', models.CharField(help_text='Please enter the features of package', max_length=200, verbose_name='Package Feature')),
            ],
            options={
                'verbose_name_plural': 'Package Features Section',
            },
        ),
        migrations.CreateModel(
            name='packageSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Sender's Name.", max_length=50, verbose_name="Sender's Name")),
                ('email', models.EmailField(help_text="Sender's Email.", max_length=254, verbose_name="Sender's Email")),
                ('phone', models.CharField(default='', help_text="Sender's Phone Number.", max_length=15, verbose_name="Sender's Phone Number")),
                ('selectedPackage', models.CharField(help_text='Preferred Package.', max_length=80, verbose_name='Selected Package')),
                ('selectedLocation', models.CharField(help_text='Preferred location.', max_length=25, verbose_name='Selected Location')),
            ],
            options={
                'verbose_name_plural': 'Package Space Form',
            },
        ),
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotionTitle', models.CharField(blank=True, help_text='Please enter your promotion title here.', max_length=500, verbose_name='Promotion Title')),
                ('promotionImage', models.ImageField(help_text='Please upload the promotion image', upload_to='../media/images/promotions/', verbose_name='Promotion Image')),
                ('promotionText', models.TextField(default='Promotion detail', help_text='Please enter the detail of promotion.', max_length=500, verbose_name='Promotion Detail')),
                ('promotionLocation', models.CharField(blank=True, help_text='Please enter the location of promotion.', max_length=100, verbose_name='Promotion Location')),
                ('promotionStartDate', models.DateField(blank=True, help_text='Please select the starting date of promotion.', verbose_name='promotion Starting Date')),
                ('promotionEndDate', models.DateField(blank=True, help_text='Please select the starting date of promotion.', verbose_name='promotion Ending Date')),
                ('status', models.CharField(choices=[('', ''), ('Active', 'Active'), ('Inactive', 'Inactive')], default='', help_text='Select the status of promotion.', max_length=10, verbose_name='Promotion Status')),
                ('slug', models.SlugField(default='', unique=True)),
            ],
            options={
                'verbose_name_plural': 'Promotions Section',
            },
        ),
        migrations.CreateModel(
            name='TopBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopBarNum', models.CharField(help_text='Enter phone number to display on TopBar.', max_length=30, verbose_name='Top Bar Number')),
            ],
            options={
                'verbose_name_plural': 'Top Bar',
            },
        ),
        migrations.CreateModel(
            name='PricingRawalpindi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PackageNameRWP', models.CharField(help_text='Please enter the package name.', max_length=50, verbose_name='Package Name')),
                ('PackageImageRWP', models.ImageField(help_text='Please upload the image for package.', upload_to='../media/images/pricing/', verbose_name='Package Image')),
                ('PackagePrice', models.IntegerField(help_text='Please enter the price for this particular package.', verbose_name='Price')),
                ('discountedPriceRWP', models.IntegerField(blank=True, help_text='Please enter the discounted price for this particular package.', null=True, verbose_name='Discounted Price')),
                ('discountedPercentRWP', models.CharField(blank=True, help_text='Please enter the Discounted Percentage of this particular package.(e.g: 20%)', max_length=10, null=True, verbose_name='Discounted Percent')),
                ('discountedDateRWP', models.DateField(blank=True, help_text='Please select the validity of discount for this particular package.', null=True, verbose_name='Discount Validity')),
                ('PackageFeature', models.ManyToManyField(help_text='Please select the features for your particular package.', to='lp7.PackagePriceFeatures')),
            ],
            options={
                'verbose_name_plural': 'Pricing Rawalpindi Section',
            },
        ),
        migrations.CreateModel(
            name='PricingIslamabad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PackageNameISD', models.CharField(help_text='Please enter the package name.', max_length=50, verbose_name='Package Name')),
                ('PackageImageISD', models.ImageField(help_text='Please upload the image for package.', upload_to='../media/images/pricing/', verbose_name='Package Image')),
                ('PackagePrice', models.IntegerField(help_text='Please enter the price for this particular package.', verbose_name='Price')),
                ('discountedPriceISD', models.IntegerField(blank=True, help_text='Please enter the discounted price for this particular package.', null=True, verbose_name='Discounted Price')),
                ('discountedPercentISD', models.CharField(blank=True, help_text='Please enter the Discounted Percentage of this particular package.(e.g: 20%)', max_length=10, null=True, verbose_name='Discounted Percent')),
                ('discountedDateISD', models.DateField(blank=True, help_text='Please select the validity of discount for this particular package.', null=True, verbose_name='Discount Validity')),
                ('PackageFeature', models.ManyToManyField(help_text='Please select the features for your particular package.', to='lp7.PackagePriceFeatures')),
            ],
            options={
                'verbose_name_plural': 'Pricing Islamabad Section',
            },
        ),
    ]
