# Generated by Django 2.2.7 on 2019-11-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lp7', '0003_auto_20191127_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='top_bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_top_bar', models.CharField(help_text='Enter phone number to display on TopBar.', max_length=30, verbose_name='Top Bar Number')),
            ],
            options={
                'verbose_name_plural': 'Top Bar Section',
            },
        ),
        migrations.DeleteModel(
            name='TopBar',
        ),
    ]
