# Generated by Django 2.2.7 on 2019-11-27 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lp7', '0004_auto_20191127_1414'),
    ]

    operations = [
        migrations.DeleteModel(
            name='top_bar',
        ),
    ]
